name: store data from "https://api.data.gov.sg/v1/transport/carpark-availability" every hour

on:
  schedule:
    - cron: "* */1 * * *"
  workflow_dispatch:
  
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name : Set correct time
        run: sudo timedatectl set-timezone Asia/Singapore
      - name: Run Scraper
        run: python script.py
      - name: Commit files
        uses: EndBug/add-and-commit@v8
        with:
          default_author: github_actions
        
